server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      max-lifetime: 30000
      maximum-pool-size: 10
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

# 配置日志  输出到控制台
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
