server:
  port: 8080

person:
  lastName: zhangsan
  age: 18
  boss: false
  birth: 2020/4/4
  maps: {k1: v1, k2: 12}
  lists:
    - zhangsan
    - lisi
    - wangwu
  dog:
    name: dogname
    age: 2
spring:
  profiles:
    active: dev
---
server:
  port: 8081
spring:
  profiles: dev

---

server:
  port: 8082
spring:
  profiles: prod